modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="zings_birdzing"
version="1.5.0"
displayName="ZiNG's Birdzing"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"
enumExtensions="META-INF/enumextensions.json"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "zings_birdzing.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.zings_birdzing]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.95,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.zings_birdzing]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration